version: '3.4'
services:
  web:
    build: .
    working_dir: /app
    volumes:
    - ./:/app
    environment:
    - GIN_MODE=debug
    - WEB_SEVER_HOST=:8080
    - WEB_SEVER_TIMEOUT=5
    ports:
    - "8080:8080"
  #  links:
  #  - redis
  #redis:
  #  image: redis
  #  ports:
  #  - "6379:6379"
