version: '3.4'
services:
  web:
    build: .
    working_dir: /app
    volumes:
    - ./:/app
    env_file:
    - .env
    ports:
    - "8080:8080"
  #  links:
  #  - redis
  #redis:
  #  image: redis
  #  ports:
  #  - "6379:6379"
